[project]
name = "pcos-detection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pandas>=2.2.3",
    "scikit-learn>=1.6.1",
    "streamlit>=1.41.1",
]

[tool.uv.workspace]
members = ["backend"]
