[project]
name = "pcos-detection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "streamlit>=1.41.1",
    "scikit-learn",
    "pandas",
    "fastapi[standard]",
    "uvicorn[standard]>=0.34.0",
]
